In [ ]:
%pip install -r requirement.txt

In [2]:
import numpy as np
import pandas as pd 
from scipy import stats
from scipy.stats import ttest_ind

### T-tests 
- Running Two-Sample T-Test below to compare means of two independent datasets

In [6]:
# Dummy data to demonstrate t-tests 

df1 = pd.DataFrame([np.random.random(100) for x in range(100)])
df2 = pd.DataFrame([np.random.random(100) for x in range(100)])
print(df1.shape, df2.shape)
df1.head()

(100, 100) (100, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.720911,0.327144,0.901315,0.227855,0.095268,0.875585,0.813702,0.855072,0.814673,0.130670,...,0.627073,0.509758,0.469820,0.934142,0.785818,0.938076,0.591108,0.394172,0.834963,0.072555
1,0.866920,0.219012,0.913173,0.434981,0.203574,0.287377,0.064636,0.188676,0.054724,0.223692,...,0.188091,0.180530,0.454390,0.175497,0.964754,0.850603,0.863482,0.816247,0.763649,0.375783
2,0.755359,0.325140,0.522274,0.991156,0.518000,0.656280,0.938788,0.217645,0.007446,0.196062,...,0.683212,0.296556,0.049224,0.009693,0.065399,0.056561,0.126136,0.316749,0.256883,0.018884
3,0.538228,0.344170,0.853752,0.321205,0.870330,0.563305,0.818840,0.821250,0.765122,0.442783,...,0.962851,0.787421,0.452859,0.240931,0.576336,0.534805,0.155733,0.348127,0.229548,0.736291
4,0.900444,0.802245,0.329473,0.948515,0.728076,0.207458,0.786518,0.310275,0.374969,0.988878,...,0.554102,0.087122,0.873213,0.002164,0.260929,0.822049,0.335726,0.199132,0.466659,0.316280

In [7]:
# for a given row inside of df1, is it the same as the row inside df2? 
# Critical value = 0.05, or alpha of 5% 
# goal: report when the p-value is less than 5% (meaning that we have sufficient evidence to say that columns are different)

def test_columns(alpha=0.05): 
    num_diff = 0 
    for col in df1.columns:
        # Run ttest between the 2 dataframes 
        teststat, pval = ttest_ind(df1[col], df2[col])
        # Check the pvalue versus the alpha
        if pval <= alpha: 
            # Print out if they're different and increment the num_diff
            print("col {} is statistically significantly different at alpha={}, pval={}".format(col, alpha, pval))
            num_diff = num_diff+1 

    # Print out summary stats 
    print("Total number different was {}, which is {}%".format(num_diff, float(num_diff)/len(df1.columns)*100))

# Call the function 
test_columns()

col 3 is statistically significantly different at alpha=0.05, pval=0.0021012869453391437
col 45 is statistically significantly different at alpha=0.05, pval=0.03060032696992823
col 66 is statistically significantly different at alpha=0.05, pval=0.046907189002305075
col 77 is statistically significantly different at alpha=0.05, pval=0.007128893981319593
col 96 is statistically significantly different at alpha=0.05, pval=0.018301343984686667
Total number different was 5, which is 5.0%